version: '1.0'
services:
   spring-app:
      build:
         context: .
         dockerfile: Dockerfile
         args:
            JAR_FILE: spring-app.jar
      image: 1602047/spring-app:v3.0 # username/repo:tag
      ports:
         - 8080:8080
         - 8099:8010
      environment:
         - TZ=Asia/Dhaka
