apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-logging
  namespace: logging-space
  labels:
    app: kibana-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-logging
  template:
    metadata:
      labels:
        app: kibana-logging
    spec:
      containers:
      - name: kibana-logging
        image: docker.elastic.co/kibana/kibana-oss:6.2.4
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch-logging:9200
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: logging-stack-config
                key: DEFAULT_TIMEZONE
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: logging-space
  labels:
    app: kibana-logging
spec:
  type: NodePort
  ports:
  - port: 5601
    targetPort: 5601
    protocol: TCP
    nodePort: 30001
  selector:
    app: kibana-logging
