apiVersion: v1
kind: ConfigMap
metadata:
  name: beat-config
  namespace: sohel-space
data:
  filebeat: |
    filebeat.inputs:
      - type: log
        paths:
          - /tmp/service-logs/service.json

    output:
      logstash:
        hosts: ["logstash-service.logging-space.svc.cluster.local:5044"]
