apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-stack-ingress
  namespace: sohel-space
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spring-app-service
            port:
              number: 8080
